services:
  - type: web
    name: glideon-ecommerce
    env: node
    region: oregon
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: glideon-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET  
        generateValue: true
    healthCheckPath: /
    
databases:
  - name: glideon-db
    databaseName: glideon
    user: glideon_user
    region: oregon
    plan: starter